data.w <- read.csv2("sample_within.csv")
data.b <- read.csv2("sample_between.csv")
mq.w <- metaqap("origin",data.w)
mq.w.s <- metaqap.stats.fisher(mq.w$q,mq.w$info)
mq.b <- metaqap("origin",data.b)
mq.b.s <- metaqap.stats.fisher(mq.b$q,mq.b$info)
summary(mq.w.s)
summary(mq.b.s)
summary(metaqap.diff(mq.w.s,mq.b.s))
